project_id = "fdpandnzblzvamhsoukt"

[functions.update-floor-plan]
verify_jwt = false

[functions.import-complexes-excel]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-sitemap-index]
verify_jwt = false

[functions.generate-sitemap-static]
verify_jwt = false

[functions.generate-sitemap-complexes]
verify_jwt = false

[functions.generate-sitemap-properties]
verify_jwt = false

[functions.notify-google-sitemap]
verify_jwt = false
