/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeoSlugRouteImport } from './routes/$seoSlug'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdaugaRouteImport } from './routes/adauga'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnunturiRouteImport } from './routes/anunturi'
import { Route as ApartamenteRouteImport } from './routes/apartamente'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AppRouteImport } from './routes/app'
import { Route as CalculatorCreditRouteImport } from './routes/calculator-credit'
import { Route as CarieraRouteImport } from './routes/cariera'
import { Route as CarteVizitaRouteImport } from './routes/carte-vizita'
import { Route as ComparatieComplexuriMilitariChiajnaRouteImport } from './routes/comparatie-complexuri-militari-chiajna'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CosturiTranzactieImobiliaraRouteImport } from './routes/costuri-tranzactie-imobiliara'
import { Route as DeCeSaNeAlegiRouteImport } from './routes/de-ce-sa-ne-alegi'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as EurocasaResidenceRouteImport } from './routes/eurocasa-residence'
import { Route as ExtensieChromePrivacyRouteImport } from './routes/extensie-chrome-privacy'
import { Route as FacilitatiMilitariResidenceRouteImport } from './routes/facilitati-militari-residence'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GarsoniereMilitariResidenceRouteImport } from './routes/garsoniere-militari-residence'
import { Route as GhidMilitariResidenceRouteImport } from './routes/ghid-militari-residence'
import { Route as GhidNouaCasa2024RouteImport } from './routes/ghid-noua-casa-2024'
import { Route as IntrebariFrecventeRouteImport } from './routes/intrebari-frecvente'
import { Route as MilitariResidenceRouteImport } from './routes/militari-residence'
import { Route as MilitariVsChiajnaComparatieRouteImport } from './routes/militari-vs-chiajna-comparatie'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as OfertaChar123idChar125RouteImport } from './routes/oferta-{$id}'
import { Route as OferteRouteImport } from './routes/oferte'
import { Route as PareriMilitariResidenceRouteImport } from './routes/pareri-militari-residence'
import { Route as PoliticaConfidentialitateRouteImport } from './routes/politica-confidentialitate'
import { Route as PoliticiEditorialeRouteImport } from './routes/politici-editoriale'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RenewResidenceRouteImport } from './routes/renew-residence'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapComplexeDotxmlRouteImport } from './routes/sitemap-complexe[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapImmofluxDotxmlRouteImport } from './routes/sitemap-immoflux[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapPropertiesDotxmlRouteImport } from './routes/sitemap-properties[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermeniConditiiRouteImport } from './routes/termeni-conditii'
import { Route as TopAnsambluriRezidentialeSector6RouteImport } from './routes/top-ansambluri-rezidentiale-sector-6'
import { Route as ViataInMilitariResidenceRouteImport } from './routes/viata-in-militari-residence'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgentVocalRouteImport } from './routes/admin/agent-vocal'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminCartiVizitaRouteImport } from './routes/admin/carti-vizita'
import { Route as AdminClientiRouteImport } from './routes/admin/clienti'
import { Route as AdminComisioaneRouteImport } from './routes/admin/comisioane'
import { Route as AdminContracteRouteImport } from './routes/admin/contracte'
import { Route as AdminFacebookGroupsRouteImport } from './routes/admin/facebook-groups'
import { Route as AdminFacebookQueueRouteImport } from './routes/admin/facebook-queue'
import { Route as AdminGestiuneChiriiRouteImport } from './routes/admin/gestiune-chirii'
import { Route as AdminImmofluxRouteImport } from './routes/admin/immoflux'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminInstaleazaRouteImport } from './routes/admin/instaleaza'
import { Route as AdminInventarPresetatRouteImport } from './routes/admin/inventar-presetat'
import { Route as AdminIstoricRouteImport } from './routes/admin/istoric'
import { Route as AdminMarketingAiRouteImport } from './routes/admin/marketing-ai'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminProprietatiRouteImport } from './routes/admin/proprietati'
import { Route as AdminRapoarteRouteImport } from './routes/admin/rapoarte'
import { Route as AdminSetariRouteImport } from './routes/admin/setari'
import { Route as AdminVirtualStagingRouteImport } from './routes/admin/virtual-staging'
import { Route as AdminVizionariRouteImport } from './routes/admin/vizionari'
import { Route as AdminVizualizariProprietatiRouteImport } from './routes/admin/vizualizari-proprietati'
import { Route as AdminWatermarkRouteImport } from './routes/admin/watermark'
import { Route as AnsambluriRezidentialeSlugRouteImport } from './routes/ansambluri-rezidentiale/$slug'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCautaRouteImport } from './routes/app/cauta'
import { Route as AppComplexeRouteImport } from './routes/app/complexe'
import { Route as AppContRouteImport } from './routes/app/cont'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ComplexeIndexRouteImport } from './routes/complexe/index'
import { Route as ComplexeSlugRouteImport } from './routes/complexe/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as ProiecteIndexRouteImport } from './routes/proiecte/index'
import { Route as ProiecteIdRouteImport } from './routes/proiecte/$id'
import { Route as ProprietateSlugRouteImport } from './routes/proprietate/$slug'
import { Route as ProprietatiIndexRouteImport } from './routes/proprietati/index'
import { Route as ProprietatiSlugRouteImport } from './routes/proprietati/$slug'
import { Route as SignTokenRouteImport } from './routes/sign/$token'
import { Route as AdminComplexeIndexRouteImport } from './routes/admin/complexe/index'
import { Route as AdminComplexeAddRouteImport } from './routes/admin/complexe/add'
import { Route as AdminGestiuneChiriiIndexRouteImport } from './routes/admin/gestiune-chirii/index'
import { Route as AdminGestiuneChiriiCalendarRouteImport } from './routes/admin/gestiune-chirii/calendar'
import { Route as AdminGestiuneChiriiChiriasiRouteImport } from './routes/admin/gestiune-chirii/chiriasi'
import { Route as AdminGestiuneChiriiInventarRouteImport } from './routes/admin/gestiune-chirii/inventar'
import { Route as AdminGestiuneChiriiProprietariRouteImport } from './routes/admin/gestiune-chirii/proprietari'
import { Route as AdminGestiuneChiriiRaportRouteImport } from './routes/admin/gestiune-chirii/raport'
import { Route as AdminGestiuneChiriiServiciiRouteImport } from './routes/admin/gestiune-chirii/servicii'
import { Route as AdminGestiuneChiriiTicheteRouteImport } from './routes/admin/gestiune-chirii/tichete'
import { Route as AdminGestiuneChiriiUtilitatiRouteImport } from './routes/admin/gestiune-chirii/utilitati'
import { Route as ApiPublicAuthEmailHookRouteImport } from './routes/api/public/auth-email-hook'
import { Route as ApiPublicOgImageRouteImport } from './routes/api/public/og-image'
import { Route as ApiPublicOgMetaRouteImport } from './routes/api/public/og-meta'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AppComplexIdRouteImport } from './routes/app/complex/$id'
import { Route as AppProprietateSlugRouteImport } from './routes/app/proprietate/$slug'
import { Route as AdminComplexeIdIndexRouteImport } from './routes/admin/complexe/$id/index'
import { Route as AdminComplexeIdEditRouteImport } from './routes/admin/complexe/$id/edit'
import { Route as AdminGestiuneChiriiProprietatiIndexRouteImport } from './routes/admin/gestiune-chirii/proprietati/index'
import { Route as AdminGestiuneChiriiProprietatiAdaugaRouteImport } from './routes/admin/gestiune-chirii/proprietati/adauga'
import { Route as ApiPublicFbQueueSplatRouteImport } from './routes/api/public/fb-queue/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSlugRoute = SeoSlugRouteImport.update({
  id: '/$seoSlug',
  path: '/$seoSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaugaRoute = AdaugaRouteImport.update({
  id: '/adauga',
  path: '/adauga',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunturiRoute = AnunturiRouteImport.update({
  id: '/anunturi',
  path: '/anunturi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamenteRoute = ApartamenteRouteImport.update({
  id: '/apartamente',
  path: '/apartamente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorCreditRoute = CalculatorCreditRouteImport.update({
  id: '/calculator-credit',
  path: '/calculator-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CarieraRoute = CarieraRouteImport.update({
  id: '/cariera',
  path: '/cariera',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteVizitaRoute = CarteVizitaRouteImport.update({
  id: '/carte-vizita',
  path: '/carte-vizita',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatieComplexuriMilitariChiajnaRoute =
  ComparatieComplexuriMilitariChiajnaRouteImport.update({
    id: '/comparatie-complexuri-militari-chiajna',
    path: '/comparatie-complexuri-militari-chiajna',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CosturiTranzactieImobiliaraRoute =
  CosturiTranzactieImobiliaraRouteImport.update({
    id: '/costuri-tranzactie-imobiliara',
    path: '/costuri-tranzactie-imobiliara',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeCeSaNeAlegiRoute = DeCeSaNeAlegiRouteImport.update({
  id: '/de-ce-sa-ne-alegi',
  path: '/de-ce-sa-ne-alegi',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const EurocasaResidenceRoute = EurocasaResidenceRouteImport.update({
  id: '/eurocasa-residence',
  path: '/eurocasa-residence',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensieChromePrivacyRoute = ExtensieChromePrivacyRouteImport.update({
  id: '/extensie-chrome-privacy',
  path: '/extensie-chrome-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatiMilitariResidenceRoute =
  FacilitatiMilitariResidenceRouteImport.update({
    id: '/facilitati-militari-residence',
    path: '/facilitati-militari-residence',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GarsoniereMilitariResidenceRoute =
  GarsoniereMilitariResidenceRouteImport.update({
    id: '/garsoniere-militari-residence',
    path: '/garsoniere-militari-residence',
    getParentRoute: () => rootRouteImport,
  } as any)
const GhidMilitariResidenceRoute = GhidMilitariResidenceRouteImport.update({
  id: '/ghid-militari-residence',
  path: '/ghid-militari-residence',
  getParentRoute: () => rootRouteImport,
} as any)
const GhidNouaCasa2024Route = GhidNouaCasa2024RouteImport.update({
  id: '/ghid-noua-casa-2024',
  path: '/ghid-noua-casa-2024',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrebariFrecventeRoute = IntrebariFrecventeRouteImport.update({
  id: '/intrebari-frecvente',
  path: '/intrebari-frecvente',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitariResidenceRoute = MilitariResidenceRouteImport.update({
  id: '/militari-residence',
  path: '/militari-residence',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitariVsChiajnaComparatieRoute =
  MilitariVsChiajnaComparatieRouteImport.update({
    id: '/militari-vs-chiajna-comparatie',
    path: '/militari-vs-chiajna-comparatie',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaChar123idChar125Route = OfertaChar123idChar125RouteImport.update({
  id: '/oferta-{$id}',
  path: '/oferta-{$id}',
  getParentRoute: () => rootRouteImport,
} as any)
const OferteRoute = OferteRouteImport.update({
  id: '/oferte',
  path: '/oferte',
  getParentRoute: () => rootRouteImport,
} as any)
const PareriMilitariResidenceRoute = PareriMilitariResidenceRouteImport.update({
  id: '/pareri-militari-residence',
  path: '/pareri-militari-residence',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaConfidentialitateRoute =
  PoliticaConfidentialitateRouteImport.update({
    id: '/politica-confidentialitate',
    path: '/politica-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticiEditorialeRoute = PoliticiEditorialeRouteImport.update({
  id: '/politici-editoriale',
  path: '/politici-editoriale',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewResidenceRoute = RenewResidenceRouteImport.update({
  id: '/renew-residence',
  path: '/renew-residence',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapComplexeDotxmlRoute = SitemapComplexeDotxmlRouteImport.update({
  id: '/sitemap-complexe.xml',
  path: '/sitemap-complexe.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImmofluxDotxmlRoute = SitemapImmofluxDotxmlRouteImport.update({
  id: '/sitemap-immoflux.xml',
  path: '/sitemap-immoflux.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPropertiesDotxmlRoute = SitemapPropertiesDotxmlRouteImport.update({
  id: '/sitemap-properties.xml',
  path: '/sitemap-properties.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniConditiiRoute = TermeniConditiiRouteImport.update({
  id: '/termeni-conditii',
  path: '/termeni-conditii',
  getParentRoute: () => rootRouteImport,
} as any)
const TopAnsambluriRezidentialeSector6Route =
  TopAnsambluriRezidentialeSector6RouteImport.update({
    id: '/top-ansambluri-rezidentiale-sector-6',
    path: '/top-ansambluri-rezidentiale-sector-6',
    getParentRoute: () => rootRouteImport,
  } as any)
const ViataInMilitariResidenceRoute =
  ViataInMilitariResidenceRouteImport.update({
    id: '/viata-in-militari-residence',
    path: '/viata-in-militari-residence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentVocalRoute = AdminAgentVocalRouteImport.update({
  id: '/agent-vocal',
  path: '/agent-vocal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCartiVizitaRoute = AdminCartiVizitaRouteImport.update({
  id: '/carti-vizita',
  path: '/carti-vizita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientiRoute = AdminClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComisioaneRoute = AdminComisioaneRouteImport.update({
  id: '/comisioane',
  path: '/comisioane',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContracteRoute = AdminContracteRouteImport.update({
  id: '/contracte',
  path: '/contracte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacebookGroupsRoute = AdminFacebookGroupsRouteImport.update({
  id: '/facebook-groups',
  path: '/facebook-groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacebookQueueRoute = AdminFacebookQueueRouteImport.update({
  id: '/facebook-queue',
  path: '/facebook-queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestiuneChiriiRoute = AdminGestiuneChiriiRouteImport.update({
  id: '/gestiune-chirii',
  path: '/gestiune-chirii',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImmofluxRoute = AdminImmofluxRouteImport.update({
  id: '/immoflux',
  path: '/immoflux',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstaleazaRoute = AdminInstaleazaRouteImport.update({
  id: '/instaleaza',
  path: '/instaleaza',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarPresetatRoute = AdminInventarPresetatRouteImport.update({
  id: '/inventar-presetat',
  path: '/inventar-presetat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIstoricRoute = AdminIstoricRouteImport.update({
  id: '/istoric',
  path: '/istoric',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingAiRoute = AdminMarketingAiRouteImport.update({
  id: '/marketing-ai',
  path: '/marketing-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProprietatiRoute = AdminProprietatiRouteImport.update({
  id: '/proprietati',
  path: '/proprietati',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRapoarteRoute = AdminRapoarteRouteImport.update({
  id: '/rapoarte',
  path: '/rapoarte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetariRoute = AdminSetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVirtualStagingRoute = AdminVirtualStagingRouteImport.update({
  id: '/virtual-staging',
  path: '/virtual-staging',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVizionariRoute = AdminVizionariRouteImport.update({
  id: '/vizionari',
  path: '/vizionari',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVizualizariProprietatiRoute =
  AdminVizualizariProprietatiRouteImport.update({
    id: '/vizualizari-proprietati',
    path: '/vizualizari-proprietati',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWatermarkRoute = AdminWatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => AdminRoute,
} as any)
const AnsambluriRezidentialeSlugRoute =
  AnsambluriRezidentialeSlugRouteImport.update({
    id: '/ansambluri-rezidentiale/$slug',
    path: '/ansambluri-rezidentiale/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCautaRoute = AppCautaRouteImport.update({
  id: '/cauta',
  path: '/cauta',
  getParentRoute: () => AppRoute,
} as any)
const AppComplexeRoute = AppComplexeRouteImport.update({
  id: '/complexe',
  path: '/complexe',
  getParentRoute: () => AppRoute,
} as any)
const AppContRoute = AppContRouteImport.update({
  id: '/cont',
  path: '/cont',
  getParentRoute: () => AppRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexeIndexRoute = ComplexeIndexRouteImport.update({
  id: '/complexe/',
  path: '/complexe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexeSlugRoute = ComplexeSlugRouteImport.update({
  id: '/complexe/$slug',
  path: '/complexe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProiecteIndexRoute = ProiecteIndexRouteImport.update({
  id: '/proiecte/',
  path: '/proiecte/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProiecteIdRoute = ProiecteIdRouteImport.update({
  id: '/proiecte/$id',
  path: '/proiecte/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietateSlugRoute = ProprietateSlugRouteImport.update({
  id: '/proprietate/$slug',
  path: '/proprietate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietatiIndexRoute = ProprietatiIndexRouteImport.update({
  id: '/proprietati/',
  path: '/proprietati/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietatiSlugRoute = ProprietatiSlugRouteImport.update({
  id: '/proprietati/$slug',
  path: '/proprietati/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplexeIndexRoute = AdminComplexeIndexRouteImport.update({
  id: '/complexe/',
  path: '/complexe/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplexeAddRoute = AdminComplexeAddRouteImport.update({
  id: '/complexe/add',
  path: '/complexe/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestiuneChiriiIndexRoute =
  AdminGestiuneChiriiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiCalendarRoute =
  AdminGestiuneChiriiCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiChiriasiRoute =
  AdminGestiuneChiriiChiriasiRouteImport.update({
    id: '/chiriasi',
    path: '/chiriasi',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiInventarRoute =
  AdminGestiuneChiriiInventarRouteImport.update({
    id: '/inventar',
    path: '/inventar',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiProprietariRoute =
  AdminGestiuneChiriiProprietariRouteImport.update({
    id: '/proprietari',
    path: '/proprietari',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiRaportRoute =
  AdminGestiuneChiriiRaportRouteImport.update({
    id: '/raport',
    path: '/raport',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiServiciiRoute =
  AdminGestiuneChiriiServiciiRouteImport.update({
    id: '/servicii',
    path: '/servicii',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiTicheteRoute =
  AdminGestiuneChiriiTicheteRouteImport.update({
    id: '/tichete',
    path: '/tichete',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiUtilitatiRoute =
  AdminGestiuneChiriiUtilitatiRouteImport.update({
    id: '/utilitati',
    path: '/utilitati',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const ApiPublicAuthEmailHookRoute = ApiPublicAuthEmailHookRouteImport.update({
  id: '/api/public/auth-email-hook',
  path: '/api/public/auth-email-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgImageRoute = ApiPublicOgImageRouteImport.update({
  id: '/api/public/og-image',
  path: '/api/public/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgMetaRoute = ApiPublicOgMetaRouteImport.update({
  id: '/api/public/og-meta',
  path: '/api/public/og-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComplexIdRoute = AppComplexIdRouteImport.update({
  id: '/complex/$id',
  path: '/complex/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProprietateSlugRoute = AppProprietateSlugRouteImport.update({
  id: '/proprietate/$slug',
  path: '/proprietate/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminComplexeIdIndexRoute = AdminComplexeIdIndexRouteImport.update({
  id: '/complexe/$id/',
  path: '/complexe/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplexeIdEditRoute = AdminComplexeIdEditRouteImport.update({
  id: '/complexe/$id/edit',
  path: '/complexe/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestiuneChiriiProprietatiIndexRoute =
  AdminGestiuneChiriiProprietatiIndexRouteImport.update({
    id: '/proprietati/',
    path: '/proprietati/',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const AdminGestiuneChiriiProprietatiAdaugaRoute =
  AdminGestiuneChiriiProprietatiAdaugaRouteImport.update({
    id: '/proprietati/adauga',
    path: '/proprietati/adauga',
    getParentRoute: () => AdminGestiuneChiriiRoute,
  } as any)
const ApiPublicFbQueueSplatRoute = ApiPublicFbQueueSplatRouteImport.update({
  id: '/api/public/fb-queue/$',
  path: '/api/public/fb-queue/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/adauga': typeof AdaugaRoute
  '/admin': typeof AdminRouteWithChildren
  '/anunturi': typeof AnunturiRoute
  '/apartamente': typeof ApartamenteRoute
  '/api-keys': typeof ApiKeysRoute
  '/app': typeof AppRouteWithChildren
  '/calculator-credit': typeof CalculatorCreditRoute
  '/cariera': typeof CarieraRoute
  '/carte-vizita': typeof CarteVizitaRoute
  '/comparatie-complexuri-militari-chiajna': typeof ComparatieComplexuriMilitariChiajnaRoute
  '/contact': typeof ContactRoute
  '/costuri-tranzactie-imobiliara': typeof CosturiTranzactieImobiliaraRoute
  '/de-ce-sa-ne-alegi': typeof DeCeSaNeAlegiRoute
  '/despre-noi': typeof DespreNoiRoute
  '/eurocasa-residence': typeof EurocasaResidenceRoute
  '/extensie-chrome-privacy': typeof ExtensieChromePrivacyRoute
  '/facilitati-militari-residence': typeof FacilitatiMilitariResidenceRoute
  '/faq': typeof FaqRoute
  '/garsoniere-militari-residence': typeof GarsoniereMilitariResidenceRoute
  '/ghid-militari-residence': typeof GhidMilitariResidenceRoute
  '/ghid-noua-casa-2024': typeof GhidNouaCasa2024Route
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/militari-residence': typeof MilitariResidenceRoute
  '/militari-vs-chiajna-comparatie': typeof MilitariVsChiajnaComparatieRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/oferta-{$id}': typeof OfertaChar123idChar125Route
  '/oferte': typeof OferteRoute
  '/pareri-militari-residence': typeof PareriMilitariResidenceRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politici-editoriale': typeof PoliticiEditorialeRoute
  '/properties': typeof PropertiesRoute
  '/renew-residence': typeof RenewResidenceRoute
  '/services': typeof ServicesRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-complexe.xml': typeof SitemapComplexeDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-immoflux.xml': typeof SitemapImmofluxDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-properties.xml': typeof SitemapPropertiesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-conditii': typeof TermeniConditiiRoute
  '/top-ansambluri-rezidentiale-sector-6': typeof TopAnsambluriRezidentialeSector6Route
  '/viata-in-militari-residence': typeof ViataInMilitariResidenceRoute
  '/admin/agent-vocal': typeof AdminAgentVocalRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carti-vizita': typeof AdminCartiVizitaRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/comisioane': typeof AdminComisioaneRoute
  '/admin/contracte': typeof AdminContracteRoute
  '/admin/facebook-groups': typeof AdminFacebookGroupsRoute
  '/admin/facebook-queue': typeof AdminFacebookQueueRoute
  '/admin/gestiune-chirii': typeof AdminGestiuneChiriiRouteWithChildren
  '/admin/immoflux': typeof AdminImmofluxRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/instaleaza': typeof AdminInstaleazaRoute
  '/admin/inventar-presetat': typeof AdminInventarPresetatRoute
  '/admin/istoric': typeof AdminIstoricRoute
  '/admin/marketing-ai': typeof AdminMarketingAiRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/proprietati': typeof AdminProprietatiRoute
  '/admin/rapoarte': typeof AdminRapoarteRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/virtual-staging': typeof AdminVirtualStagingRoute
  '/admin/vizionari': typeof AdminVizionariRoute
  '/admin/vizualizari-proprietati': typeof AdminVizualizariProprietatiRoute
  '/admin/watermark': typeof AdminWatermarkRoute
  '/ansambluri-rezidentiale/$slug': typeof AnsambluriRezidentialeSlugRoute
  '/app/cauta': typeof AppCautaRoute
  '/app/complexe': typeof AppComplexeRoute
  '/app/cont': typeof AppContRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/complexe/$slug': typeof ComplexeSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/proiecte/$id': typeof ProiecteIdRoute
  '/proprietate/$slug': typeof ProprietateSlugRoute
  '/proprietati/$slug': typeof ProprietatiSlugRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/complexe/': typeof ComplexeIndexRoute
  '/news/': typeof NewsIndexRoute
  '/proiecte/': typeof ProiecteIndexRoute
  '/proprietati/': typeof ProprietatiIndexRoute
  '/admin/complexe/add': typeof AdminComplexeAddRoute
  '/admin/gestiune-chirii/calendar': typeof AdminGestiuneChiriiCalendarRoute
  '/admin/gestiune-chirii/chiriasi': typeof AdminGestiuneChiriiChiriasiRoute
  '/admin/gestiune-chirii/inventar': typeof AdminGestiuneChiriiInventarRoute
  '/admin/gestiune-chirii/proprietari': typeof AdminGestiuneChiriiProprietariRoute
  '/admin/gestiune-chirii/raport': typeof AdminGestiuneChiriiRaportRoute
  '/admin/gestiune-chirii/servicii': typeof AdminGestiuneChiriiServiciiRoute
  '/admin/gestiune-chirii/tichete': typeof AdminGestiuneChiriiTicheteRoute
  '/admin/gestiune-chirii/utilitati': typeof AdminGestiuneChiriiUtilitatiRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/og-image': typeof ApiPublicOgImageRoute
  '/api/public/og-meta': typeof ApiPublicOgMetaRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/complex/$id': typeof AppComplexIdRoute
  '/app/proprietate/$slug': typeof AppProprietateSlugRoute
  '/admin/complexe/': typeof AdminComplexeIndexRoute
  '/admin/gestiune-chirii/': typeof AdminGestiuneChiriiIndexRoute
  '/admin/complexe/$id/edit': typeof AdminComplexeIdEditRoute
  '/admin/gestiune-chirii/proprietati/adauga': typeof AdminGestiuneChiriiProprietatiAdaugaRoute
  '/api/public/fb-queue/$': typeof ApiPublicFbQueueSplatRoute
  '/admin/complexe/$id/': typeof AdminComplexeIdIndexRoute
  '/admin/gestiune-chirii/proprietati/': typeof AdminGestiuneChiriiProprietatiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/adauga': typeof AdaugaRoute
  '/anunturi': typeof AnunturiRoute
  '/apartamente': typeof ApartamenteRoute
  '/api-keys': typeof ApiKeysRoute
  '/calculator-credit': typeof CalculatorCreditRoute
  '/cariera': typeof CarieraRoute
  '/carte-vizita': typeof CarteVizitaRoute
  '/comparatie-complexuri-militari-chiajna': typeof ComparatieComplexuriMilitariChiajnaRoute
  '/contact': typeof ContactRoute
  '/costuri-tranzactie-imobiliara': typeof CosturiTranzactieImobiliaraRoute
  '/de-ce-sa-ne-alegi': typeof DeCeSaNeAlegiRoute
  '/despre-noi': typeof DespreNoiRoute
  '/eurocasa-residence': typeof EurocasaResidenceRoute
  '/extensie-chrome-privacy': typeof ExtensieChromePrivacyRoute
  '/facilitati-militari-residence': typeof FacilitatiMilitariResidenceRoute
  '/faq': typeof FaqRoute
  '/garsoniere-militari-residence': typeof GarsoniereMilitariResidenceRoute
  '/ghid-militari-residence': typeof GhidMilitariResidenceRoute
  '/ghid-noua-casa-2024': typeof GhidNouaCasa2024Route
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/militari-residence': typeof MilitariResidenceRoute
  '/militari-vs-chiajna-comparatie': typeof MilitariVsChiajnaComparatieRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/oferta-{$id}': typeof OfertaChar123idChar125Route
  '/oferte': typeof OferteRoute
  '/pareri-militari-residence': typeof PareriMilitariResidenceRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politici-editoriale': typeof PoliticiEditorialeRoute
  '/properties': typeof PropertiesRoute
  '/renew-residence': typeof RenewResidenceRoute
  '/services': typeof ServicesRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-complexe.xml': typeof SitemapComplexeDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-immoflux.xml': typeof SitemapImmofluxDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-properties.xml': typeof SitemapPropertiesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-conditii': typeof TermeniConditiiRoute
  '/top-ansambluri-rezidentiale-sector-6': typeof TopAnsambluriRezidentialeSector6Route
  '/viata-in-militari-residence': typeof ViataInMilitariResidenceRoute
  '/admin/agent-vocal': typeof AdminAgentVocalRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carti-vizita': typeof AdminCartiVizitaRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/comisioane': typeof AdminComisioaneRoute
  '/admin/contracte': typeof AdminContracteRoute
  '/admin/facebook-groups': typeof AdminFacebookGroupsRoute
  '/admin/facebook-queue': typeof AdminFacebookQueueRoute
  '/admin/immoflux': typeof AdminImmofluxRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/instaleaza': typeof AdminInstaleazaRoute
  '/admin/inventar-presetat': typeof AdminInventarPresetatRoute
  '/admin/istoric': typeof AdminIstoricRoute
  '/admin/marketing-ai': typeof AdminMarketingAiRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/proprietati': typeof AdminProprietatiRoute
  '/admin/rapoarte': typeof AdminRapoarteRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/virtual-staging': typeof AdminVirtualStagingRoute
  '/admin/vizionari': typeof AdminVizionariRoute
  '/admin/vizualizari-proprietati': typeof AdminVizualizariProprietatiRoute
  '/admin/watermark': typeof AdminWatermarkRoute
  '/ansambluri-rezidentiale/$slug': typeof AnsambluriRezidentialeSlugRoute
  '/app/cauta': typeof AppCautaRoute
  '/app/complexe': typeof AppComplexeRoute
  '/app/cont': typeof AppContRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/complexe/$slug': typeof ComplexeSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/proiecte/$id': typeof ProiecteIdRoute
  '/proprietate/$slug': typeof ProprietateSlugRoute
  '/proprietati/$slug': typeof ProprietatiSlugRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/complexe': typeof ComplexeIndexRoute
  '/news': typeof NewsIndexRoute
  '/proiecte': typeof ProiecteIndexRoute
  '/proprietati': typeof ProprietatiIndexRoute
  '/admin/complexe/add': typeof AdminComplexeAddRoute
  '/admin/gestiune-chirii/calendar': typeof AdminGestiuneChiriiCalendarRoute
  '/admin/gestiune-chirii/chiriasi': typeof AdminGestiuneChiriiChiriasiRoute
  '/admin/gestiune-chirii/inventar': typeof AdminGestiuneChiriiInventarRoute
  '/admin/gestiune-chirii/proprietari': typeof AdminGestiuneChiriiProprietariRoute
  '/admin/gestiune-chirii/raport': typeof AdminGestiuneChiriiRaportRoute
  '/admin/gestiune-chirii/servicii': typeof AdminGestiuneChiriiServiciiRoute
  '/admin/gestiune-chirii/tichete': typeof AdminGestiuneChiriiTicheteRoute
  '/admin/gestiune-chirii/utilitati': typeof AdminGestiuneChiriiUtilitatiRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/og-image': typeof ApiPublicOgImageRoute
  '/api/public/og-meta': typeof ApiPublicOgMetaRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/complex/$id': typeof AppComplexIdRoute
  '/app/proprietate/$slug': typeof AppProprietateSlugRoute
  '/admin/complexe': typeof AdminComplexeIndexRoute
  '/admin/gestiune-chirii': typeof AdminGestiuneChiriiIndexRoute
  '/admin/complexe/$id/edit': typeof AdminComplexeIdEditRoute
  '/admin/gestiune-chirii/proprietati/adauga': typeof AdminGestiuneChiriiProprietatiAdaugaRoute
  '/api/public/fb-queue/$': typeof ApiPublicFbQueueSplatRoute
  '/admin/complexe/$id': typeof AdminComplexeIdIndexRoute
  '/admin/gestiune-chirii/proprietati': typeof AdminGestiuneChiriiProprietatiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/adauga': typeof AdaugaRoute
  '/admin': typeof AdminRouteWithChildren
  '/anunturi': typeof AnunturiRoute
  '/apartamente': typeof ApartamenteRoute
  '/api-keys': typeof ApiKeysRoute
  '/app': typeof AppRouteWithChildren
  '/calculator-credit': typeof CalculatorCreditRoute
  '/cariera': typeof CarieraRoute
  '/carte-vizita': typeof CarteVizitaRoute
  '/comparatie-complexuri-militari-chiajna': typeof ComparatieComplexuriMilitariChiajnaRoute
  '/contact': typeof ContactRoute
  '/costuri-tranzactie-imobiliara': typeof CosturiTranzactieImobiliaraRoute
  '/de-ce-sa-ne-alegi': typeof DeCeSaNeAlegiRoute
  '/despre-noi': typeof DespreNoiRoute
  '/eurocasa-residence': typeof EurocasaResidenceRoute
  '/extensie-chrome-privacy': typeof ExtensieChromePrivacyRoute
  '/facilitati-militari-residence': typeof FacilitatiMilitariResidenceRoute
  '/faq': typeof FaqRoute
  '/garsoniere-militari-residence': typeof GarsoniereMilitariResidenceRoute
  '/ghid-militari-residence': typeof GhidMilitariResidenceRoute
  '/ghid-noua-casa-2024': typeof GhidNouaCasa2024Route
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/militari-residence': typeof MilitariResidenceRoute
  '/militari-vs-chiajna-comparatie': typeof MilitariVsChiajnaComparatieRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/oferta-{$id}': typeof OfertaChar123idChar125Route
  '/oferte': typeof OferteRoute
  '/pareri-militari-residence': typeof PareriMilitariResidenceRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/politici-editoriale': typeof PoliticiEditorialeRoute
  '/properties': typeof PropertiesRoute
  '/renew-residence': typeof RenewResidenceRoute
  '/services': typeof ServicesRoute
  '/servicii': typeof ServiciiRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-complexe.xml': typeof SitemapComplexeDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-immoflux.xml': typeof SitemapImmofluxDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-properties.xml': typeof SitemapPropertiesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-conditii': typeof TermeniConditiiRoute
  '/top-ansambluri-rezidentiale-sector-6': typeof TopAnsambluriRezidentialeSector6Route
  '/viata-in-militari-residence': typeof ViataInMilitariResidenceRoute
  '/admin/agent-vocal': typeof AdminAgentVocalRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/carti-vizita': typeof AdminCartiVizitaRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/comisioane': typeof AdminComisioaneRoute
  '/admin/contracte': typeof AdminContracteRoute
  '/admin/facebook-groups': typeof AdminFacebookGroupsRoute
  '/admin/facebook-queue': typeof AdminFacebookQueueRoute
  '/admin/gestiune-chirii': typeof AdminGestiuneChiriiRouteWithChildren
  '/admin/immoflux': typeof AdminImmofluxRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/instaleaza': typeof AdminInstaleazaRoute
  '/admin/inventar-presetat': typeof AdminInventarPresetatRoute
  '/admin/istoric': typeof AdminIstoricRoute
  '/admin/marketing-ai': typeof AdminMarketingAiRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/proprietati': typeof AdminProprietatiRoute
  '/admin/rapoarte': typeof AdminRapoarteRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/virtual-staging': typeof AdminVirtualStagingRoute
  '/admin/vizionari': typeof AdminVizionariRoute
  '/admin/vizualizari-proprietati': typeof AdminVizualizariProprietatiRoute
  '/admin/watermark': typeof AdminWatermarkRoute
  '/ansambluri-rezidentiale/$slug': typeof AnsambluriRezidentialeSlugRoute
  '/app/cauta': typeof AppCautaRoute
  '/app/complexe': typeof AppComplexeRoute
  '/app/cont': typeof AppContRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/complexe/$slug': typeof ComplexeSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/proiecte/$id': typeof ProiecteIdRoute
  '/proprietate/$slug': typeof ProprietateSlugRoute
  '/proprietati/$slug': typeof ProprietatiSlugRoute
  '/sign/$token': typeof SignTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/complexe/': typeof ComplexeIndexRoute
  '/news/': typeof NewsIndexRoute
  '/proiecte/': typeof ProiecteIndexRoute
  '/proprietati/': typeof ProprietatiIndexRoute
  '/admin/complexe/add': typeof AdminComplexeAddRoute
  '/admin/gestiune-chirii/calendar': typeof AdminGestiuneChiriiCalendarRoute
  '/admin/gestiune-chirii/chiriasi': typeof AdminGestiuneChiriiChiriasiRoute
  '/admin/gestiune-chirii/inventar': typeof AdminGestiuneChiriiInventarRoute
  '/admin/gestiune-chirii/proprietari': typeof AdminGestiuneChiriiProprietariRoute
  '/admin/gestiune-chirii/raport': typeof AdminGestiuneChiriiRaportRoute
  '/admin/gestiune-chirii/servicii': typeof AdminGestiuneChiriiServiciiRoute
  '/admin/gestiune-chirii/tichete': typeof AdminGestiuneChiriiTicheteRoute
  '/admin/gestiune-chirii/utilitati': typeof AdminGestiuneChiriiUtilitatiRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/og-image': typeof ApiPublicOgImageRoute
  '/api/public/og-meta': typeof ApiPublicOgMetaRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/app/complex/$id': typeof AppComplexIdRoute
  '/app/proprietate/$slug': typeof AppProprietateSlugRoute
  '/admin/complexe/': typeof AdminComplexeIndexRoute
  '/admin/gestiune-chirii/': typeof AdminGestiuneChiriiIndexRoute
  '/admin/complexe/$id/edit': typeof AdminComplexeIdEditRoute
  '/admin/gestiune-chirii/proprietati/adauga': typeof AdminGestiuneChiriiProprietatiAdaugaRoute
  '/api/public/fb-queue/$': typeof ApiPublicFbQueueSplatRoute
  '/admin/complexe/$id/': typeof AdminComplexeIdIndexRoute
  '/admin/gestiune-chirii/proprietati/': typeof AdminGestiuneChiriiProprietatiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$seoSlug'
    | '/404'
    | '/about'
    | '/adauga'
    | '/admin'
    | '/anunturi'
    | '/apartamente'
    | '/api-keys'
    | '/app'
    | '/calculator-credit'
    | '/cariera'
    | '/carte-vizita'
    | '/comparatie-complexuri-militari-chiajna'
    | '/contact'
    | '/costuri-tranzactie-imobiliara'
    | '/de-ce-sa-ne-alegi'
    | '/despre-noi'
    | '/eurocasa-residence'
    | '/extensie-chrome-privacy'
    | '/facilitati-militari-residence'
    | '/faq'
    | '/garsoniere-militari-residence'
    | '/ghid-militari-residence'
    | '/ghid-noua-casa-2024'
    | '/intrebari-frecvente'
    | '/militari-residence'
    | '/militari-vs-chiajna-comparatie'
    | '/news-sitemap.xml'
    | '/oferta-{$id}'
    | '/oferte'
    | '/pareri-militari-residence'
    | '/politica-confidentialitate'
    | '/politici-editoriale'
    | '/properties'
    | '/renew-residence'
    | '/services'
    | '/servicii'
    | '/sitemap'
    | '/sitemap-complexe.xml'
    | '/sitemap-images.xml'
    | '/sitemap-immoflux.xml'
    | '/sitemap-index.xml'
    | '/sitemap-properties.xml'
    | '/sitemap.xml'
    | '/termeni-conditii'
    | '/top-ansambluri-rezidentiale-sector-6'
    | '/viata-in-militari-residence'
    | '/admin/agent-vocal'
    | '/admin/blog'
    | '/admin/carti-vizita'
    | '/admin/clienti'
    | '/admin/comisioane'
    | '/admin/contracte'
    | '/admin/facebook-groups'
    | '/admin/facebook-queue'
    | '/admin/gestiune-chirii'
    | '/admin/immoflux'
    | '/admin/inbox'
    | '/admin/instaleaza'
    | '/admin/inventar-presetat'
    | '/admin/istoric'
    | '/admin/marketing-ai'
    | '/admin/news'
    | '/admin/proprietati'
    | '/admin/rapoarte'
    | '/admin/setari'
    | '/admin/virtual-staging'
    | '/admin/vizionari'
    | '/admin/vizualizari-proprietati'
    | '/admin/watermark'
    | '/ansambluri-rezidentiale/$slug'
    | '/app/cauta'
    | '/app/complexe'
    | '/app/cont'
    | '/blog/$slug'
    | '/complexe/$slug'
    | '/news/$slug'
    | '/proiecte/$id'
    | '/proprietate/$slug'
    | '/proprietati/$slug'
    | '/sign/$token'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/complexe/'
    | '/news/'
    | '/proiecte/'
    | '/proprietati/'
    | '/admin/complexe/add'
    | '/admin/gestiune-chirii/calendar'
    | '/admin/gestiune-chirii/chiriasi'
    | '/admin/gestiune-chirii/inventar'
    | '/admin/gestiune-chirii/proprietari'
    | '/admin/gestiune-chirii/raport'
    | '/admin/gestiune-chirii/servicii'
    | '/admin/gestiune-chirii/tichete'
    | '/admin/gestiune-chirii/utilitati'
    | '/api/public/auth-email-hook'
    | '/api/public/og-image'
    | '/api/public/og-meta'
    | '/api/public/track'
    | '/app/complex/$id'
    | '/app/proprietate/$slug'
    | '/admin/complexe/'
    | '/admin/gestiune-chirii/'
    | '/admin/complexe/$id/edit'
    | '/admin/gestiune-chirii/proprietati/adauga'
    | '/api/public/fb-queue/$'
    | '/admin/complexe/$id/'
    | '/admin/gestiune-chirii/proprietati/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$seoSlug'
    | '/404'
    | '/about'
    | '/adauga'
    | '/anunturi'
    | '/apartamente'
    | '/api-keys'
    | '/calculator-credit'
    | '/cariera'
    | '/carte-vizita'
    | '/comparatie-complexuri-militari-chiajna'
    | '/contact'
    | '/costuri-tranzactie-imobiliara'
    | '/de-ce-sa-ne-alegi'
    | '/despre-noi'
    | '/eurocasa-residence'
    | '/extensie-chrome-privacy'
    | '/facilitati-militari-residence'
    | '/faq'
    | '/garsoniere-militari-residence'
    | '/ghid-militari-residence'
    | '/ghid-noua-casa-2024'
    | '/intrebari-frecvente'
    | '/militari-residence'
    | '/militari-vs-chiajna-comparatie'
    | '/news-sitemap.xml'
    | '/oferta-{$id}'
    | '/oferte'
    | '/pareri-militari-residence'
    | '/politica-confidentialitate'
    | '/politici-editoriale'
    | '/properties'
    | '/renew-residence'
    | '/services'
    | '/servicii'
    | '/sitemap'
    | '/sitemap-complexe.xml'
    | '/sitemap-images.xml'
    | '/sitemap-immoflux.xml'
    | '/sitemap-index.xml'
    | '/sitemap-properties.xml'
    | '/sitemap.xml'
    | '/termeni-conditii'
    | '/top-ansambluri-rezidentiale-sector-6'
    | '/viata-in-militari-residence'
    | '/admin/agent-vocal'
    | '/admin/blog'
    | '/admin/carti-vizita'
    | '/admin/clienti'
    | '/admin/comisioane'
    | '/admin/contracte'
    | '/admin/facebook-groups'
    | '/admin/facebook-queue'
    | '/admin/immoflux'
    | '/admin/inbox'
    | '/admin/instaleaza'
    | '/admin/inventar-presetat'
    | '/admin/istoric'
    | '/admin/marketing-ai'
    | '/admin/news'
    | '/admin/proprietati'
    | '/admin/rapoarte'
    | '/admin/setari'
    | '/admin/virtual-staging'
    | '/admin/vizionari'
    | '/admin/vizualizari-proprietati'
    | '/admin/watermark'
    | '/ansambluri-rezidentiale/$slug'
    | '/app/cauta'
    | '/app/complexe'
    | '/app/cont'
    | '/blog/$slug'
    | '/complexe/$slug'
    | '/news/$slug'
    | '/proiecte/$id'
    | '/proprietate/$slug'
    | '/proprietati/$slug'
    | '/sign/$token'
    | '/admin'
    | '/app'
    | '/blog'
    | '/complexe'
    | '/news'
    | '/proiecte'
    | '/proprietati'
    | '/admin/complexe/add'
    | '/admin/gestiune-chirii/calendar'
    | '/admin/gestiune-chirii/chiriasi'
    | '/admin/gestiune-chirii/inventar'
    | '/admin/gestiune-chirii/proprietari'
    | '/admin/gestiune-chirii/raport'
    | '/admin/gestiune-chirii/servicii'
    | '/admin/gestiune-chirii/tichete'
    | '/admin/gestiune-chirii/utilitati'
    | '/api/public/auth-email-hook'
    | '/api/public/og-image'
    | '/api/public/og-meta'
    | '/api/public/track'
    | '/app/complex/$id'
    | '/app/proprietate/$slug'
    | '/admin/complexe'
    | '/admin/gestiune-chirii'
    | '/admin/complexe/$id/edit'
    | '/admin/gestiune-chirii/proprietati/adauga'
    | '/api/public/fb-queue/$'
    | '/admin/complexe/$id'
    | '/admin/gestiune-chirii/proprietati'
  id:
    | '__root__'
    | '/'
    | '/$seoSlug'
    | '/404'
    | '/about'
    | '/adauga'
    | '/admin'
    | '/anunturi'
    | '/apartamente'
    | '/api-keys'
    | '/app'
    | '/calculator-credit'
    | '/cariera'
    | '/carte-vizita'
    | '/comparatie-complexuri-militari-chiajna'
    | '/contact'
    | '/costuri-tranzactie-imobiliara'
    | '/de-ce-sa-ne-alegi'
    | '/despre-noi'
    | '/eurocasa-residence'
    | '/extensie-chrome-privacy'
    | '/facilitati-militari-residence'
    | '/faq'
    | '/garsoniere-militari-residence'
    | '/ghid-militari-residence'
    | '/ghid-noua-casa-2024'
    | '/intrebari-frecvente'
    | '/militari-residence'
    | '/militari-vs-chiajna-comparatie'
    | '/news-sitemap.xml'
    | '/oferta-{$id}'
    | '/oferte'
    | '/pareri-militari-residence'
    | '/politica-confidentialitate'
    | '/politici-editoriale'
    | '/properties'
    | '/renew-residence'
    | '/services'
    | '/servicii'
    | '/sitemap'
    | '/sitemap-complexe.xml'
    | '/sitemap-images.xml'
    | '/sitemap-immoflux.xml'
    | '/sitemap-index.xml'
    | '/sitemap-properties.xml'
    | '/sitemap.xml'
    | '/termeni-conditii'
    | '/top-ansambluri-rezidentiale-sector-6'
    | '/viata-in-militari-residence'
    | '/admin/agent-vocal'
    | '/admin/blog'
    | '/admin/carti-vizita'
    | '/admin/clienti'
    | '/admin/comisioane'
    | '/admin/contracte'
    | '/admin/facebook-groups'
    | '/admin/facebook-queue'
    | '/admin/gestiune-chirii'
    | '/admin/immoflux'
    | '/admin/inbox'
    | '/admin/instaleaza'
    | '/admin/inventar-presetat'
    | '/admin/istoric'
    | '/admin/marketing-ai'
    | '/admin/news'
    | '/admin/proprietati'
    | '/admin/rapoarte'
    | '/admin/setari'
    | '/admin/virtual-staging'
    | '/admin/vizionari'
    | '/admin/vizualizari-proprietati'
    | '/admin/watermark'
    | '/ansambluri-rezidentiale/$slug'
    | '/app/cauta'
    | '/app/complexe'
    | '/app/cont'
    | '/blog/$slug'
    | '/complexe/$slug'
    | '/news/$slug'
    | '/proiecte/$id'
    | '/proprietate/$slug'
    | '/proprietati/$slug'
    | '/sign/$token'
    | '/admin/'
    | '/app/'
    | '/blog/'
    | '/complexe/'
    | '/news/'
    | '/proiecte/'
    | '/proprietati/'
    | '/admin/complexe/add'
    | '/admin/gestiune-chirii/calendar'
    | '/admin/gestiune-chirii/chiriasi'
    | '/admin/gestiune-chirii/inventar'
    | '/admin/gestiune-chirii/proprietari'
    | '/admin/gestiune-chirii/raport'
    | '/admin/gestiune-chirii/servicii'
    | '/admin/gestiune-chirii/tichete'
    | '/admin/gestiune-chirii/utilitati'
    | '/api/public/auth-email-hook'
    | '/api/public/og-image'
    | '/api/public/og-meta'
    | '/api/public/track'
    | '/app/complex/$id'
    | '/app/proprietate/$slug'
    | '/admin/complexe/'
    | '/admin/gestiune-chirii/'
    | '/admin/complexe/$id/edit'
    | '/admin/gestiune-chirii/proprietati/adauga'
    | '/api/public/fb-queue/$'
    | '/admin/complexe/$id/'
    | '/admin/gestiune-chirii/proprietati/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeoSlugRoute: typeof SeoSlugRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdaugaRoute: typeof AdaugaRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnunturiRoute: typeof AnunturiRoute
  ApartamenteRoute: typeof ApartamenteRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AppRoute: typeof AppRouteWithChildren
  CalculatorCreditRoute: typeof CalculatorCreditRoute
  CarieraRoute: typeof CarieraRoute
  CarteVizitaRoute: typeof CarteVizitaRoute
  ComparatieComplexuriMilitariChiajnaRoute: typeof ComparatieComplexuriMilitariChiajnaRoute
  ContactRoute: typeof ContactRoute
  CosturiTranzactieImobiliaraRoute: typeof CosturiTranzactieImobiliaraRoute
  DeCeSaNeAlegiRoute: typeof DeCeSaNeAlegiRoute
  DespreNoiRoute: typeof DespreNoiRoute
  EurocasaResidenceRoute: typeof EurocasaResidenceRoute
  ExtensieChromePrivacyRoute: typeof ExtensieChromePrivacyRoute
  FacilitatiMilitariResidenceRoute: typeof FacilitatiMilitariResidenceRoute
  FaqRoute: typeof FaqRoute
  GarsoniereMilitariResidenceRoute: typeof GarsoniereMilitariResidenceRoute
  GhidMilitariResidenceRoute: typeof GhidMilitariResidenceRoute
  GhidNouaCasa2024Route: typeof GhidNouaCasa2024Route
  IntrebariFrecventeRoute: typeof IntrebariFrecventeRoute
  MilitariResidenceRoute: typeof MilitariResidenceRoute
  MilitariVsChiajnaComparatieRoute: typeof MilitariVsChiajnaComparatieRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  OfertaChar123idChar125Route: typeof OfertaChar123idChar125Route
  OferteRoute: typeof OferteRoute
  PareriMilitariResidenceRoute: typeof PareriMilitariResidenceRoute
  PoliticaConfidentialitateRoute: typeof PoliticaConfidentialitateRoute
  PoliticiEditorialeRoute: typeof PoliticiEditorialeRoute
  PropertiesRoute: typeof PropertiesRoute
  RenewResidenceRoute: typeof RenewResidenceRoute
  ServicesRoute: typeof ServicesRoute
  ServiciiRoute: typeof ServiciiRoute
  SitemapRoute: typeof SitemapRoute
  SitemapComplexeDotxmlRoute: typeof SitemapComplexeDotxmlRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapImmofluxDotxmlRoute: typeof SitemapImmofluxDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapPropertiesDotxmlRoute: typeof SitemapPropertiesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniConditiiRoute: typeof TermeniConditiiRoute
  TopAnsambluriRezidentialeSector6Route: typeof TopAnsambluriRezidentialeSector6Route
  ViataInMilitariResidenceRoute: typeof ViataInMilitariResidenceRoute
  AnsambluriRezidentialeSlugRoute: typeof AnsambluriRezidentialeSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ComplexeSlugRoute: typeof ComplexeSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProiecteIdRoute: typeof ProiecteIdRoute
  ProprietateSlugRoute: typeof ProprietateSlugRoute
  ProprietatiSlugRoute: typeof ProprietatiSlugRoute
  SignTokenRoute: typeof SignTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ComplexeIndexRoute: typeof ComplexeIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProiecteIndexRoute: typeof ProiecteIndexRoute
  ProprietatiIndexRoute: typeof ProprietatiIndexRoute
  ApiPublicAuthEmailHookRoute: typeof ApiPublicAuthEmailHookRoute
  ApiPublicOgImageRoute: typeof ApiPublicOgImageRoute
  ApiPublicOgMetaRoute: typeof ApiPublicOgMetaRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicFbQueueSplatRoute: typeof ApiPublicFbQueueSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seoSlug': {
      id: '/$seoSlug'
      path: '/$seoSlug'
      fullPath: '/$seoSlug'
      preLoaderRoute: typeof SeoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adauga': {
      id: '/adauga'
      path: '/adauga'
      fullPath: '/adauga'
      preLoaderRoute: typeof AdaugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunturi': {
      id: '/anunturi'
      path: '/anunturi'
      fullPath: '/anunturi'
      preLoaderRoute: typeof AnunturiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamente': {
      id: '/apartamente'
      path: '/apartamente'
      fullPath: '/apartamente'
      preLoaderRoute: typeof ApartamenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator-credit': {
      id: '/calculator-credit'
      path: '/calculator-credit'
      fullPath: '/calculator-credit'
      preLoaderRoute: typeof CalculatorCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cariera': {
      id: '/cariera'
      path: '/cariera'
      fullPath: '/cariera'
      preLoaderRoute: typeof CarieraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte-vizita': {
      id: '/carte-vizita'
      path: '/carte-vizita'
      fullPath: '/carte-vizita'
      preLoaderRoute: typeof CarteVizitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatie-complexuri-militari-chiajna': {
      id: '/comparatie-complexuri-militari-chiajna'
      path: '/comparatie-complexuri-militari-chiajna'
      fullPath: '/comparatie-complexuri-militari-chiajna'
      preLoaderRoute: typeof ComparatieComplexuriMilitariChiajnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costuri-tranzactie-imobiliara': {
      id: '/costuri-tranzactie-imobiliara'
      path: '/costuri-tranzactie-imobiliara'
      fullPath: '/costuri-tranzactie-imobiliara'
      preLoaderRoute: typeof CosturiTranzactieImobiliaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-ce-sa-ne-alegi': {
      id: '/de-ce-sa-ne-alegi'
      path: '/de-ce-sa-ne-alegi'
      fullPath: '/de-ce-sa-ne-alegi'
      preLoaderRoute: typeof DeCeSaNeAlegiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eurocasa-residence': {
      id: '/eurocasa-residence'
      path: '/eurocasa-residence'
      fullPath: '/eurocasa-residence'
      preLoaderRoute: typeof EurocasaResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensie-chrome-privacy': {
      id: '/extensie-chrome-privacy'
      path: '/extensie-chrome-privacy'
      fullPath: '/extensie-chrome-privacy'
      preLoaderRoute: typeof ExtensieChromePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitati-militari-residence': {
      id: '/facilitati-militari-residence'
      path: '/facilitati-militari-residence'
      fullPath: '/facilitati-militari-residence'
      preLoaderRoute: typeof FacilitatiMilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garsoniere-militari-residence': {
      id: '/garsoniere-militari-residence'
      path: '/garsoniere-militari-residence'
      fullPath: '/garsoniere-militari-residence'
      preLoaderRoute: typeof GarsoniereMilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid-militari-residence': {
      id: '/ghid-militari-residence'
      path: '/ghid-militari-residence'
      fullPath: '/ghid-militari-residence'
      preLoaderRoute: typeof GhidMilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid-noua-casa-2024': {
      id: '/ghid-noua-casa-2024'
      path: '/ghid-noua-casa-2024'
      fullPath: '/ghid-noua-casa-2024'
      preLoaderRoute: typeof GhidNouaCasa2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intrebari-frecvente': {
      id: '/intrebari-frecvente'
      path: '/intrebari-frecvente'
      fullPath: '/intrebari-frecvente'
      preLoaderRoute: typeof IntrebariFrecventeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/militari-residence': {
      id: '/militari-residence'
      path: '/militari-residence'
      fullPath: '/militari-residence'
      preLoaderRoute: typeof MilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/militari-vs-chiajna-comparatie': {
      id: '/militari-vs-chiajna-comparatie'
      path: '/militari-vs-chiajna-comparatie'
      fullPath: '/militari-vs-chiajna-comparatie'
      preLoaderRoute: typeof MilitariVsChiajnaComparatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta-{$id}': {
      id: '/oferta-{$id}'
      path: '/oferta-{$id}'
      fullPath: '/oferta-{$id}'
      preLoaderRoute: typeof OfertaChar123idChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferte': {
      id: '/oferte'
      path: '/oferte'
      fullPath: '/oferte'
      preLoaderRoute: typeof OferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pareri-militari-residence': {
      id: '/pareri-militari-residence'
      path: '/pareri-militari-residence'
      fullPath: '/pareri-militari-residence'
      preLoaderRoute: typeof PareriMilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-confidentialitate': {
      id: '/politica-confidentialitate'
      path: '/politica-confidentialitate'
      fullPath: '/politica-confidentialitate'
      preLoaderRoute: typeof PoliticaConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politici-editoriale': {
      id: '/politici-editoriale'
      path: '/politici-editoriale'
      fullPath: '/politici-editoriale'
      preLoaderRoute: typeof PoliticiEditorialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew-residence': {
      id: '/renew-residence'
      path: '/renew-residence'
      fullPath: '/renew-residence'
      preLoaderRoute: typeof RenewResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-complexe.xml': {
      id: '/sitemap-complexe.xml'
      path: '/sitemap-complexe.xml'
      fullPath: '/sitemap-complexe.xml'
      preLoaderRoute: typeof SitemapComplexeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-immoflux.xml': {
      id: '/sitemap-immoflux.xml'
      path: '/sitemap-immoflux.xml'
      fullPath: '/sitemap-immoflux.xml'
      preLoaderRoute: typeof SitemapImmofluxDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-properties.xml': {
      id: '/sitemap-properties.xml'
      path: '/sitemap-properties.xml'
      fullPath: '/sitemap-properties.xml'
      preLoaderRoute: typeof SitemapPropertiesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-conditii': {
      id: '/termeni-conditii'
      path: '/termeni-conditii'
      fullPath: '/termeni-conditii'
      preLoaderRoute: typeof TermeniConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-ansambluri-rezidentiale-sector-6': {
      id: '/top-ansambluri-rezidentiale-sector-6'
      path: '/top-ansambluri-rezidentiale-sector-6'
      fullPath: '/top-ansambluri-rezidentiale-sector-6'
      preLoaderRoute: typeof TopAnsambluriRezidentialeSector6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viata-in-militari-residence': {
      id: '/viata-in-militari-residence'
      path: '/viata-in-militari-residence'
      fullPath: '/viata-in-militari-residence'
      preLoaderRoute: typeof ViataInMilitariResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent-vocal': {
      id: '/admin/agent-vocal'
      path: '/agent-vocal'
      fullPath: '/admin/agent-vocal'
      preLoaderRoute: typeof AdminAgentVocalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carti-vizita': {
      id: '/admin/carti-vizita'
      path: '/carti-vizita'
      fullPath: '/admin/carti-vizita'
      preLoaderRoute: typeof AdminCartiVizitaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clienti': {
      id: '/admin/clienti'
      path: '/clienti'
      fullPath: '/admin/clienti'
      preLoaderRoute: typeof AdminClientiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comisioane': {
      id: '/admin/comisioane'
      path: '/comisioane'
      fullPath: '/admin/comisioane'
      preLoaderRoute: typeof AdminComisioaneRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracte': {
      id: '/admin/contracte'
      path: '/contracte'
      fullPath: '/admin/contracte'
      preLoaderRoute: typeof AdminContracteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facebook-groups': {
      id: '/admin/facebook-groups'
      path: '/facebook-groups'
      fullPath: '/admin/facebook-groups'
      preLoaderRoute: typeof AdminFacebookGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facebook-queue': {
      id: '/admin/facebook-queue'
      path: '/facebook-queue'
      fullPath: '/admin/facebook-queue'
      preLoaderRoute: typeof AdminFacebookQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestiune-chirii': {
      id: '/admin/gestiune-chirii'
      path: '/gestiune-chirii'
      fullPath: '/admin/gestiune-chirii'
      preLoaderRoute: typeof AdminGestiuneChiriiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/immoflux': {
      id: '/admin/immoflux'
      path: '/immoflux'
      fullPath: '/admin/immoflux'
      preLoaderRoute: typeof AdminImmofluxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instaleaza': {
      id: '/admin/instaleaza'
      path: '/instaleaza'
      fullPath: '/admin/instaleaza'
      preLoaderRoute: typeof AdminInstaleazaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventar-presetat': {
      id: '/admin/inventar-presetat'
      path: '/inventar-presetat'
      fullPath: '/admin/inventar-presetat'
      preLoaderRoute: typeof AdminInventarPresetatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/istoric': {
      id: '/admin/istoric'
      path: '/istoric'
      fullPath: '/admin/istoric'
      preLoaderRoute: typeof AdminIstoricRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing-ai': {
      id: '/admin/marketing-ai'
      path: '/marketing-ai'
      fullPath: '/admin/marketing-ai'
      preLoaderRoute: typeof AdminMarketingAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proprietati': {
      id: '/admin/proprietati'
      path: '/proprietati'
      fullPath: '/admin/proprietati'
      preLoaderRoute: typeof AdminProprietatiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapoarte': {
      id: '/admin/rapoarte'
      path: '/rapoarte'
      fullPath: '/admin/rapoarte'
      preLoaderRoute: typeof AdminRapoarteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setari': {
      id: '/admin/setari'
      path: '/setari'
      fullPath: '/admin/setari'
      preLoaderRoute: typeof AdminSetariRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/virtual-staging': {
      id: '/admin/virtual-staging'
      path: '/virtual-staging'
      fullPath: '/admin/virtual-staging'
      preLoaderRoute: typeof AdminVirtualStagingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vizionari': {
      id: '/admin/vizionari'
      path: '/vizionari'
      fullPath: '/admin/vizionari'
      preLoaderRoute: typeof AdminVizionariRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vizualizari-proprietati': {
      id: '/admin/vizualizari-proprietati'
      path: '/vizualizari-proprietati'
      fullPath: '/admin/vizualizari-proprietati'
      preLoaderRoute: typeof AdminVizualizariProprietatiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/watermark': {
      id: '/admin/watermark'
      path: '/watermark'
      fullPath: '/admin/watermark'
      preLoaderRoute: typeof AdminWatermarkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ansambluri-rezidentiale/$slug': {
      id: '/ansambluri-rezidentiale/$slug'
      path: '/ansambluri-rezidentiale/$slug'
      fullPath: '/ansambluri-rezidentiale/$slug'
      preLoaderRoute: typeof AnsambluriRezidentialeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cauta': {
      id: '/app/cauta'
      path: '/cauta'
      fullPath: '/app/cauta'
      preLoaderRoute: typeof AppCautaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complexe': {
      id: '/app/complexe'
      path: '/complexe'
      fullPath: '/app/complexe'
      preLoaderRoute: typeof AppComplexeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cont': {
      id: '/app/cont'
      path: '/cont'
      fullPath: '/app/cont'
      preLoaderRoute: typeof AppContRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexe/': {
      id: '/complexe/'
      path: '/complexe'
      fullPath: '/complexe/'
      preLoaderRoute: typeof ComplexeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexe/$slug': {
      id: '/complexe/$slug'
      path: '/complexe/$slug'
      fullPath: '/complexe/$slug'
      preLoaderRoute: typeof ComplexeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proiecte/': {
      id: '/proiecte/'
      path: '/proiecte'
      fullPath: '/proiecte/'
      preLoaderRoute: typeof ProiecteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proiecte/$id': {
      id: '/proiecte/$id'
      path: '/proiecte/$id'
      fullPath: '/proiecte/$id'
      preLoaderRoute: typeof ProiecteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietate/$slug': {
      id: '/proprietate/$slug'
      path: '/proprietate/$slug'
      fullPath: '/proprietate/$slug'
      preLoaderRoute: typeof ProprietateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietati/': {
      id: '/proprietati/'
      path: '/proprietati'
      fullPath: '/proprietati/'
      preLoaderRoute: typeof ProprietatiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietati/$slug': {
      id: '/proprietati/$slug'
      path: '/proprietati/$slug'
      fullPath: '/proprietati/$slug'
      preLoaderRoute: typeof ProprietatiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complexe/': {
      id: '/admin/complexe/'
      path: '/complexe'
      fullPath: '/admin/complexe/'
      preLoaderRoute: typeof AdminComplexeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complexe/add': {
      id: '/admin/complexe/add'
      path: '/complexe/add'
      fullPath: '/admin/complexe/add'
      preLoaderRoute: typeof AdminComplexeAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestiune-chirii/': {
      id: '/admin/gestiune-chirii/'
      path: '/'
      fullPath: '/admin/gestiune-chirii/'
      preLoaderRoute: typeof AdminGestiuneChiriiIndexRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/calendar': {
      id: '/admin/gestiune-chirii/calendar'
      path: '/calendar'
      fullPath: '/admin/gestiune-chirii/calendar'
      preLoaderRoute: typeof AdminGestiuneChiriiCalendarRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/chiriasi': {
      id: '/admin/gestiune-chirii/chiriasi'
      path: '/chiriasi'
      fullPath: '/admin/gestiune-chirii/chiriasi'
      preLoaderRoute: typeof AdminGestiuneChiriiChiriasiRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/inventar': {
      id: '/admin/gestiune-chirii/inventar'
      path: '/inventar'
      fullPath: '/admin/gestiune-chirii/inventar'
      preLoaderRoute: typeof AdminGestiuneChiriiInventarRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/proprietari': {
      id: '/admin/gestiune-chirii/proprietari'
      path: '/proprietari'
      fullPath: '/admin/gestiune-chirii/proprietari'
      preLoaderRoute: typeof AdminGestiuneChiriiProprietariRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/raport': {
      id: '/admin/gestiune-chirii/raport'
      path: '/raport'
      fullPath: '/admin/gestiune-chirii/raport'
      preLoaderRoute: typeof AdminGestiuneChiriiRaportRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/servicii': {
      id: '/admin/gestiune-chirii/servicii'
      path: '/servicii'
      fullPath: '/admin/gestiune-chirii/servicii'
      preLoaderRoute: typeof AdminGestiuneChiriiServiciiRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/tichete': {
      id: '/admin/gestiune-chirii/tichete'
      path: '/tichete'
      fullPath: '/admin/gestiune-chirii/tichete'
      preLoaderRoute: typeof AdminGestiuneChiriiTicheteRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/utilitati': {
      id: '/admin/gestiune-chirii/utilitati'
      path: '/utilitati'
      fullPath: '/admin/gestiune-chirii/utilitati'
      preLoaderRoute: typeof AdminGestiuneChiriiUtilitatiRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/api/public/auth-email-hook': {
      id: '/api/public/auth-email-hook'
      path: '/api/public/auth-email-hook'
      fullPath: '/api/public/auth-email-hook'
      preLoaderRoute: typeof ApiPublicAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og-image': {
      id: '/api/public/og-image'
      path: '/api/public/og-image'
      fullPath: '/api/public/og-image'
      preLoaderRoute: typeof ApiPublicOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og-meta': {
      id: '/api/public/og-meta'
      path: '/api/public/og-meta'
      fullPath: '/api/public/og-meta'
      preLoaderRoute: typeof ApiPublicOgMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/complex/$id': {
      id: '/app/complex/$id'
      path: '/complex/$id'
      fullPath: '/app/complex/$id'
      preLoaderRoute: typeof AppComplexIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proprietate/$slug': {
      id: '/app/proprietate/$slug'
      path: '/proprietate/$slug'
      fullPath: '/app/proprietate/$slug'
      preLoaderRoute: typeof AppProprietateSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/complexe/$id/': {
      id: '/admin/complexe/$id/'
      path: '/complexe/$id'
      fullPath: '/admin/complexe/$id/'
      preLoaderRoute: typeof AdminComplexeIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complexe/$id/edit': {
      id: '/admin/complexe/$id/edit'
      path: '/complexe/$id/edit'
      fullPath: '/admin/complexe/$id/edit'
      preLoaderRoute: typeof AdminComplexeIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestiune-chirii/proprietati/': {
      id: '/admin/gestiune-chirii/proprietati/'
      path: '/proprietati'
      fullPath: '/admin/gestiune-chirii/proprietati/'
      preLoaderRoute: typeof AdminGestiuneChiriiProprietatiIndexRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/admin/gestiune-chirii/proprietati/adauga': {
      id: '/admin/gestiune-chirii/proprietati/adauga'
      path: '/proprietati/adauga'
      fullPath: '/admin/gestiune-chirii/proprietati/adauga'
      preLoaderRoute: typeof AdminGestiuneChiriiProprietatiAdaugaRouteImport
      parentRoute: typeof AdminGestiuneChiriiRoute
    }
    '/api/public/fb-queue/$': {
      id: '/api/public/fb-queue/$'
      path: '/api/public/fb-queue/$'
      fullPath: '/api/public/fb-queue/$'
      preLoaderRoute: typeof ApiPublicFbQueueSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminGestiuneChiriiRouteChildren {
  AdminGestiuneChiriiCalendarRoute: typeof AdminGestiuneChiriiCalendarRoute
  AdminGestiuneChiriiChiriasiRoute: typeof AdminGestiuneChiriiChiriasiRoute
  AdminGestiuneChiriiInventarRoute: typeof AdminGestiuneChiriiInventarRoute
  AdminGestiuneChiriiProprietariRoute: typeof AdminGestiuneChiriiProprietariRoute
  AdminGestiuneChiriiRaportRoute: typeof AdminGestiuneChiriiRaportRoute
  AdminGestiuneChiriiServiciiRoute: typeof AdminGestiuneChiriiServiciiRoute
  AdminGestiuneChiriiTicheteRoute: typeof AdminGestiuneChiriiTicheteRoute
  AdminGestiuneChiriiUtilitatiRoute: typeof AdminGestiuneChiriiUtilitatiRoute
  AdminGestiuneChiriiIndexRoute: typeof AdminGestiuneChiriiIndexRoute
  AdminGestiuneChiriiProprietatiAdaugaRoute: typeof AdminGestiuneChiriiProprietatiAdaugaRoute
  AdminGestiuneChiriiProprietatiIndexRoute: typeof AdminGestiuneChiriiProprietatiIndexRoute
}

const AdminGestiuneChiriiRouteChildren: AdminGestiuneChiriiRouteChildren = {
  AdminGestiuneChiriiCalendarRoute: AdminGestiuneChiriiCalendarRoute,
  AdminGestiuneChiriiChiriasiRoute: AdminGestiuneChiriiChiriasiRoute,
  AdminGestiuneChiriiInventarRoute: AdminGestiuneChiriiInventarRoute,
  AdminGestiuneChiriiProprietariRoute: AdminGestiuneChiriiProprietariRoute,
  AdminGestiuneChiriiRaportRoute: AdminGestiuneChiriiRaportRoute,
  AdminGestiuneChiriiServiciiRoute: AdminGestiuneChiriiServiciiRoute,
  AdminGestiuneChiriiTicheteRoute: AdminGestiuneChiriiTicheteRoute,
  AdminGestiuneChiriiUtilitatiRoute: AdminGestiuneChiriiUtilitatiRoute,
  AdminGestiuneChiriiIndexRoute: AdminGestiuneChiriiIndexRoute,
  AdminGestiuneChiriiProprietatiAdaugaRoute:
    AdminGestiuneChiriiProprietatiAdaugaRoute,
  AdminGestiuneChiriiProprietatiIndexRoute:
    AdminGestiuneChiriiProprietatiIndexRoute,
}

const AdminGestiuneChiriiRouteWithChildren =
  AdminGestiuneChiriiRoute._addFileChildren(AdminGestiuneChiriiRouteChildren)

interface AdminRouteChildren {
  AdminAgentVocalRoute: typeof AdminAgentVocalRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCartiVizitaRoute: typeof AdminCartiVizitaRoute
  AdminClientiRoute: typeof AdminClientiRoute
  AdminComisioaneRoute: typeof AdminComisioaneRoute
  AdminContracteRoute: typeof AdminContracteRoute
  AdminFacebookGroupsRoute: typeof AdminFacebookGroupsRoute
  AdminFacebookQueueRoute: typeof AdminFacebookQueueRoute
  AdminGestiuneChiriiRoute: typeof AdminGestiuneChiriiRouteWithChildren
  AdminImmofluxRoute: typeof AdminImmofluxRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminInstaleazaRoute: typeof AdminInstaleazaRoute
  AdminInventarPresetatRoute: typeof AdminInventarPresetatRoute
  AdminIstoricRoute: typeof AdminIstoricRoute
  AdminMarketingAiRoute: typeof AdminMarketingAiRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProprietatiRoute: typeof AdminProprietatiRoute
  AdminRapoarteRoute: typeof AdminRapoarteRoute
  AdminSetariRoute: typeof AdminSetariRoute
  AdminVirtualStagingRoute: typeof AdminVirtualStagingRoute
  AdminVizionariRoute: typeof AdminVizionariRoute
  AdminVizualizariProprietatiRoute: typeof AdminVizualizariProprietatiRoute
  AdminWatermarkRoute: typeof AdminWatermarkRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminComplexeAddRoute: typeof AdminComplexeAddRoute
  AdminComplexeIndexRoute: typeof AdminComplexeIndexRoute
  AdminComplexeIdEditRoute: typeof AdminComplexeIdEditRoute
  AdminComplexeIdIndexRoute: typeof AdminComplexeIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentVocalRoute: AdminAgentVocalRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCartiVizitaRoute: AdminCartiVizitaRoute,
  AdminClientiRoute: AdminClientiRoute,
  AdminComisioaneRoute: AdminComisioaneRoute,
  AdminContracteRoute: AdminContracteRoute,
  AdminFacebookGroupsRoute: AdminFacebookGroupsRoute,
  AdminFacebookQueueRoute: AdminFacebookQueueRoute,
  AdminGestiuneChiriiRoute: AdminGestiuneChiriiRouteWithChildren,
  AdminImmofluxRoute: AdminImmofluxRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminInstaleazaRoute: AdminInstaleazaRoute,
  AdminInventarPresetatRoute: AdminInventarPresetatRoute,
  AdminIstoricRoute: AdminIstoricRoute,
  AdminMarketingAiRoute: AdminMarketingAiRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProprietatiRoute: AdminProprietatiRoute,
  AdminRapoarteRoute: AdminRapoarteRoute,
  AdminSetariRoute: AdminSetariRoute,
  AdminVirtualStagingRoute: AdminVirtualStagingRoute,
  AdminVizionariRoute: AdminVizionariRoute,
  AdminVizualizariProprietatiRoute: AdminVizualizariProprietatiRoute,
  AdminWatermarkRoute: AdminWatermarkRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminComplexeAddRoute: AdminComplexeAddRoute,
  AdminComplexeIndexRoute: AdminComplexeIndexRoute,
  AdminComplexeIdEditRoute: AdminComplexeIdEditRoute,
  AdminComplexeIdIndexRoute: AdminComplexeIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCautaRoute: typeof AppCautaRoute
  AppComplexeRoute: typeof AppComplexeRoute
  AppContRoute: typeof AppContRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComplexIdRoute: typeof AppComplexIdRoute
  AppProprietateSlugRoute: typeof AppProprietateSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCautaRoute: AppCautaRoute,
  AppComplexeRoute: AppComplexeRoute,
  AppContRoute: AppContRoute,
  AppIndexRoute: AppIndexRoute,
  AppComplexIdRoute: AppComplexIdRoute,
  AppProprietateSlugRoute: AppProprietateSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeoSlugRoute: SeoSlugRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdaugaRoute: AdaugaRoute,
  AdminRoute: AdminRouteWithChildren,
  AnunturiRoute: AnunturiRoute,
  ApartamenteRoute: ApartamenteRoute,
  ApiKeysRoute: ApiKeysRoute,
  AppRoute: AppRouteWithChildren,
  CalculatorCreditRoute: CalculatorCreditRoute,
  CarieraRoute: CarieraRoute,
  CarteVizitaRoute: CarteVizitaRoute,
  ComparatieComplexuriMilitariChiajnaRoute:
    ComparatieComplexuriMilitariChiajnaRoute,
  ContactRoute: ContactRoute,
  CosturiTranzactieImobiliaraRoute: CosturiTranzactieImobiliaraRoute,
  DeCeSaNeAlegiRoute: DeCeSaNeAlegiRoute,
  DespreNoiRoute: DespreNoiRoute,
  EurocasaResidenceRoute: EurocasaResidenceRoute,
  ExtensieChromePrivacyRoute: ExtensieChromePrivacyRoute,
  FacilitatiMilitariResidenceRoute: FacilitatiMilitariResidenceRoute,
  FaqRoute: FaqRoute,
  GarsoniereMilitariResidenceRoute: GarsoniereMilitariResidenceRoute,
  GhidMilitariResidenceRoute: GhidMilitariResidenceRoute,
  GhidNouaCasa2024Route: GhidNouaCasa2024Route,
  IntrebariFrecventeRoute: IntrebariFrecventeRoute,
  MilitariResidenceRoute: MilitariResidenceRoute,
  MilitariVsChiajnaComparatieRoute: MilitariVsChiajnaComparatieRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  OfertaChar123idChar125Route: OfertaChar123idChar125Route,
  OferteRoute: OferteRoute,
  PareriMilitariResidenceRoute: PareriMilitariResidenceRoute,
  PoliticaConfidentialitateRoute: PoliticaConfidentialitateRoute,
  PoliticiEditorialeRoute: PoliticiEditorialeRoute,
  PropertiesRoute: PropertiesRoute,
  RenewResidenceRoute: RenewResidenceRoute,
  ServicesRoute: ServicesRoute,
  ServiciiRoute: ServiciiRoute,
  SitemapRoute: SitemapRoute,
  SitemapComplexeDotxmlRoute: SitemapComplexeDotxmlRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapImmofluxDotxmlRoute: SitemapImmofluxDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapPropertiesDotxmlRoute: SitemapPropertiesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniConditiiRoute: TermeniConditiiRoute,
  TopAnsambluriRezidentialeSector6Route: TopAnsambluriRezidentialeSector6Route,
  ViataInMilitariResidenceRoute: ViataInMilitariResidenceRoute,
  AnsambluriRezidentialeSlugRoute: AnsambluriRezidentialeSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  ComplexeSlugRoute: ComplexeSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProiecteIdRoute: ProiecteIdRoute,
  ProprietateSlugRoute: ProprietateSlugRoute,
  ProprietatiSlugRoute: ProprietatiSlugRoute,
  SignTokenRoute: SignTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  ComplexeIndexRoute: ComplexeIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProiecteIndexRoute: ProiecteIndexRoute,
  ProprietatiIndexRoute: ProprietatiIndexRoute,
  ApiPublicAuthEmailHookRoute: ApiPublicAuthEmailHookRoute,
  ApiPublicOgImageRoute: ApiPublicOgImageRoute,
  ApiPublicOgMetaRoute: ApiPublicOgMetaRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicFbQueueSplatRoute: ApiPublicFbQueueSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
