// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-properties.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function client() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false } }
  );
}
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Caut\u0103 propriet\u0103\u021Bi",
  description: "Caut\u0103 propriet\u0103\u021Bi imobiliare din catalogul MVA Imobiliare. Filtre op\u021Bionale: num\u0103r camere, pre\u021B min/max EUR, loca\u021Bie (text), doar recomandate.",
  inputSchema: {
    rooms: z.number().int().min(1).max(10).nullable().describe("Num\u0103r de camere"),
    min_price: z.number().min(0).nullable().describe("Pre\u021B minim EUR"),
    max_price: z.number().min(0).nullable().describe("Pre\u021B maxim EUR"),
    location: z.string().nullable().describe("Text c\u0103utat \xEEn loca\u021Bie (ex: Militari)"),
    featured_only: z.boolean().nullable().describe("Doar oferte recomandate"),
    limit: z.number().int().min(1).max(50).nullable().describe("Num\u0103r maxim rezultate (default 10)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ rooms, min_price, max_price, location, featured_only, limit }) => {
    const sb = client();
    let q = sb.from("catalog_offers").select("id, title, location, city, zone, price_min, price_max, rooms, surface_min, surface_max, currency, is_featured, slug, availability_status").eq("availability_status", "available").limit(limit ?? 10);
    if (rooms) q = q.eq("rooms", rooms);
    if (min_price) q = q.gte("price_min", min_price);
    if (max_price) q = q.lte("price_min", max_price);
    if (location) q = q.ilike("location", `%${location}%`);
    if (featured_only) q = q.eq("is_featured", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Eroare: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { properties: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.78.0";
function client2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false } }
  );
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Detalii proprietate",
  description: "Returneaz\u0103 detaliile complete pentru o proprietate identificat\u0103 prin slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug-ul propriet\u0103\u021Bii (ex: garsoniera-45mp-bucuresti-timisoara-439b)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const sb = client2();
    const { data, error } = await sb.from("catalog_offers").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Eroare: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Proprietatea nu a fost g\u0103sit\u0103." }], isError: true };
    const url = `https://mvaimobiliare.ro/proprietati/${slug}`;
    return {
      content: [{ type: "text", text: JSON.stringify({ ...data, url }, null, 2) }],
      structuredContent: { property: data, url }
    };
  }
});

// src/lib/mcp/tools/list-complexes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.78.0";
function client3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false } }
  );
}
var list_complexes_default = defineTool3({
  name: "list_complexes",
  title: "List\u0103 ansambluri reziden\u021Biale",
  description: "Returneaz\u0103 ansamblurile reziden\u021Biale (complexuri) disponibile \xEEn catalog.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).nullable().describe("Num\u0103r maxim rezultate (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const sb = client3();
    const { data, error } = await sb.from("projects").select("id, name, location, description, status, slug").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: `Eroare: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { complexes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact_info_default = defineTool4({
  name: "contact_info",
  title: "Informa\u021Bii de contact MVA",
  description: "Returneaz\u0103 informa\u021Biile oficiale de contact ale agen\u021Biei MVA Imobiliare.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "MVA Imobiliare",
      phone: "+40 767 941 512",
      whatsapp: "https://wa.me/40767941512",
      email: "contact@mvaimobiliare.ro",
      website: "https://mvaimobiliare.ro",
      area: "Bucure\u0219ti (Militari, Sector 6), Chiajna \u0219i Ilfov",
      since: 2016
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mva-imobiliare-mcp",
  title: "MVA Imobiliare MCP",
  version: "0.1.0",
  instructions: "Acces la catalogul de propriet\u0103\u021Bi MVA Imobiliare (Bucure\u0219ti - Militari, Sector 6, Chiajna, Ilfov). Folose\u0219te `search_properties` pentru filtrare, `get_property` pentru detalii dup\u0103 slug, `list_complexes` pentru ansambluri reziden\u021Biale \u0219i `contact_info` pentru date de contact.",
  tools: [search_properties_default, get_property_default, list_complexes_default, contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
