-- Add missing columns for XML imported properties
ALTER TABLE public.catalog_offers
ADD COLUMN IF NOT EXISTS floor integer,
ADD COLUMN IF NOT EXISTS total_floors integer,
ADD COLUMN IF NOT EXISTS bathrooms integer,
ADD COLUMN IF NOT EXISTS year_built integer,
ADD COLUMN IF NOT EXISTS property_type text,
ADD COLUMN IF NOT EXISTS building_type text,
ADD COLUMN IF NOT EXISTS compartment text,
ADD COLUMN IF NOT EXISTS heating text,
ADD COLUMN IF NOT EXISTS parking integer,
ADD COLUMN IF NOT EXISTS balconies integer,
ADD COLUMN IF NOT EXISTS furnished text,
ADD COLUMN IF NOT EXISTS external_id text,
ADD COLUMN IF NOT EXISTS source_url text,
ADD COLUMN IF NOT EXISTS zone text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS latitude numeric,
ADD COLUMN IF NOT EXISTS longitude numeric,
ADD COLUMN IF NOT EXISTS agent text,
ADD COLUMN IF NOT EXISTS agency text,
ADD COLUMN IF NOT EXISTS surface_land integer,
ADD COLUMN IF NOT EXISTS comfort text,
ADD COLUMN IF NOT EXISTS video text,
ADD COLUMN IF NOT EXISTS virtual_tour text;