CREATE TABLE public.immoflux_codes (
  code integer PRIMARY KEY,
  group_key text NOT NULL,
  group_label text NOT NULL,
  label text,
  source text NOT NULL DEFAULT 'docs',
  first_seen timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE ON public.immoflux_codes TO authenticated;
GRANT ALL ON public.immoflux_codes TO service_role;

ALTER TABLE public.immoflux_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read immoflux codes"
ON public.immoflux_codes FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated can insert immoflux codes"
ON public.immoflux_codes FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated can update immoflux codes"
ON public.immoflux_codes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER update_immoflux_codes_updated_at
BEFORE UPDATE ON public.immoflux_codes
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.catalog_offers ADD COLUMN IF NOT EXISTS resolved_features jsonb;

INSERT INTO public.immoflux_codes (code, group_key, group_label, label, source) VALUES
(10001,'utilitati','Utilități','Curent','docs'),
(10002,'utilitati','Utilități','Apă','docs'),
(10003,'utilitati','Utilități','Canalizare','docs'),
(10004,'utilitati','Utilități','Gaz','docs'),
(10005,'utilitati','Utilități','Puț','docs'),
(10006,'utilitati','Utilități','Fosă septică','docs'),
(10007,'utilitati','Utilități','Curent trifazic','docs'),
(10009,'utilitati','Utilități','CATV','docs'),
(10010,'utilitati','Utilități','Telefon','docs'),
(10011,'utilitati','Utilități','Telefon internațional','docs'),
(10012,'utilitati','Utilități','Acces internet','docs'),
(10013,'utilitati','Utilități','Fibră optică','docs'),
(10014,'utilitati','Utilități','Telefon internațional','docs'),
(10015,'utilitati','Utilități','Utilități în zonă','docs'),
(10016,'utilitati','Utilități','Sistem irigație','docs'),
(10101,'incalzire','Sistem încălzire','Termoficare','docs'),
(10102,'incalzire','Sistem încălzire','Centrală proprie','docs'),
(10103,'incalzire','Sistem încălzire','Centrală imobil','docs'),
(10104,'incalzire','Sistem încălzire','Convectoare','docs'),
(10105,'incalzire','Sistem încălzire','Sobă teracotă','docs'),
(10106,'incalzire','Sistem încălzire','Centrală pe lemne','docs'),
(10107,'incalzire','Sistem încălzire','Încălzire pardoseală','docs'),
(10108,'incalzire','Sistem încălzire','Calorifere','docs'),
(10109,'incalzire','Sistem încălzire','Șemineu','docs'),
(10201,'climatizare','Climatizare','Aer condiționat','docs'),
(10202,'climatizare','Climatizare','Ventiloconvectoare','docs'),
(10203,'climatizare','Climatizare','Aeroterme','docs'),
(10301,'teren','Teren','Oportunitate de investiție','docs'),
(10302,'teren','Teren','Construcție demolabilă','docs'),
(10303,'teren','Teren','Parcelabil','docs'),
(10304,'teren','Teren','La șosea','docs'),
(10305,'teren','Teren','Acces auto','docs'),
(10306,'teren','Teren','Teren împrejmuit','docs'),
(20001,'izolatie','Izolație','Izolație exterior','docs'),
(20002,'izolatie','Izolație','Izolație interior','docs'),
(20003,'izolatie','Izolație','Bloc izolat termic','docs'),
(20101,'pereti','Pereți','Pereți vopsea lavabilă','docs'),
(20102,'pereti','Pereți','Pereți var','docs'),
(20103,'pereti','Pereți','Pereți faianță','docs'),
(20104,'pereti','Pereți','Pereți lambriu','docs'),
(20105,'pereti','Pereți','Pereți tapet','docs'),
(20106,'pereti','Pereți','Pereți marmură','docs'),
(20107,'pereti','Pereți','Pereți humă','docs'),
(20108,'pereti','Pereți','Pereți vinarom','docs'),
(20201,'podele','Podele','Parchet','docs'),
(20202,'podele','Podele','Gresie','docs'),
(20203,'podele','Podele','Marmură','docs'),
(20204,'podele','Podele','Mochetă','docs'),
(20205,'podele','Podele','Dușumea','docs'),
(20206,'podele','Podele','Linoleum','docs'),
(20301,'stare','Stare finisaje','Finisat','docs'),
(20302,'stare','Stare finisaje','Gri','docs'),
(20303,'stare','Stare finisaje','Roșu','docs'),
(20304,'stare','Stare finisaje','Stare bună','docs'),
(20305,'stare','Stare finisaje','Necesită renovare','docs'),
(20306,'stare','Stare finisaje','Renovat','docs'),
(20401,'ferestre','Ferestre','Ferestre PVC','docs'),
(20402,'ferestre','Ferestre','Ferestre lemn','docs'),
(20403,'ferestre','Ferestre','Ferestre aluminiu','docs'),
(20501,'jaluzele','Jaluzele','Jaluzele verticale','docs'),
(20502,'jaluzele','Jaluzele','Jaluzele orizontale','docs'),
(20601,'rulouri','Rulouri','Rulouri aluminiu','docs'),
(20602,'rulouri','Rulouri','Rulouri lemn','docs'),
(20603,'rulouri','Rulouri','Rulouri PVC','docs'),
(20701,'usa_intrare','Ușă intrare','Ușă intrare metal','docs'),
(20702,'usa_intrare','Ușă intrare','Ușă intrare lemn','docs'),
(20703,'usa_intrare','Ușă intrare','Ușă intrare PVC','docs'),
(20704,'usa_intrare','Ușă intrare','Ușă intrare PAL','docs'),
(20801,'iluminat','Iluminat','Lămpi','docs'),
(20802,'iluminat','Iluminat','Spoturi','docs'),
(20803,'iluminat','Iluminat','Aplice','docs'),
(20804,'iluminat','Iluminat','Iluminat exterior','docs'),
(20805,'iluminat','Iluminat','Lumină naturală','docs'),
(20901,'usi_interior','Uși interior','Uși interior celulare','docs'),
(20902,'usi_interior','Uși interior','Uși interior lemn','docs'),
(20903,'usi_interior','Uși interior','Uși interior panel','docs'),
(20904,'usi_interior','Uși interior','Uși interior PVC','docs'),
(20905,'usi_interior','Uși interior','Uși interior sticlă','docs'),
(20906,'usi_interior','Uși interior','Uși interior metal','docs'),
(21001,'acoperis','Acoperiș','Acoperiș Lindab','docs'),
(21002,'acoperis','Acoperiș','Acoperiș țiglă','docs'),
(21003,'acoperis','Acoperiș','Terasă','docs'),
(21004,'acoperis','Acoperiș','Acoperiș tablă','docs'),
(21005,'acoperis','Acoperiș','Acoperiș carton','docs'),
(21006,'acoperis','Acoperiș','Șindrilă bituminoasă','docs'),
(30001,'spatii','Spații','Terasă','docs'),
(30002,'spatii','Spații','WC serviciu','docs'),
(30003,'spatii','Spații','Boxă la subsol','docs'),
(30004,'spatii','Spații','Debara','docs'),
(30011,'spatii','Spații','Pivniță','docs'),
(30012,'spatii','Spații','Cramă','docs'),
(30013,'spatii','Spații','Spațiu depozitare','docs'),
(30014,'spatii','Spații','Dressing','docs'),
(30015,'spatii','Spații','WC serviciu','docs'),
(30016,'spatii','Spații','Anexe','docs'),
(30017,'spatii','Spații','Dependințe','docs'),
(30021,'spatii','Spații','Pivniță','docs'),
(30022,'spatii','Spații','Cramă','docs'),
(30023,'spatii','Spații','Spațiu depozitare','docs'),
(30024,'spatii','Spații','Anexe','docs'),
(30025,'spatii','Spații','Dependințe','docs'),
(30026,'spatii','Spații','Parcare proprie','docs'),
(30027,'spatii','Spații','Parcare acoperită','docs'),
(30028,'spatii','Spații','Spațiu verde amenajat','docs'),
(30101,'bucatarie','Bucătărie','Bucătărie mobilată','docs'),
(30102,'bucatarie','Bucătărie','Bucătărie parțial mobilată','docs'),
(30103,'bucatarie','Bucătărie','Bucătărie utilată','docs'),
(30104,'bucatarie','Bucătărie','Bucătărie parțial utilată','docs'),
(30105,'bucatarie','Bucătărie','Bucătărie nemobilată','docs'),
(30106,'bucatarie','Bucătărie','Bucătărie neutilată','docs'),
(30201,'contorizare','Contorizare','Apometre','docs'),
(30202,'contorizare','Contorizare','Contor căldură','docs'),
(30203,'contorizare','Contorizare','Contor gaz','docs'),
(30301,'mobilat','Mobilat','Nemobilat','docs'),
(30302,'mobilat','Mobilat','Parțial mobilat','docs'),
(30303,'mobilat','Mobilat','Complet mobilat','docs'),
(30304,'mobilat','Mobilat','Mobilat lux','docs'),
(30401,'imobil','Imobil','Interfon','docs'),
(30402,'imobil','Imobil','Videointerfon','docs'),
(30403,'imobil','Imobil','Lift','docs'),
(30404,'imobil','Imobil','Spații agrement','docs'),
(30405,'imobil','Imobil','Saună','docs'),
(30406,'imobil','Imobil','SPA','docs'),
(30407,'imobil','Imobil','Acoperiș','docs'),
(30408,'imobil','Imobil','Curte','docs'),
(30409,'imobil','Imobil','Curte comună','docs'),
(30410,'imobil','Imobil','Grădină','docs'),
(30411,'imobil','Imobil','Piscină interioară','docs'),
(30412,'imobil','Imobil','Piscină exterioară','docs'),
(30413,'imobil','Imobil','Uscătorie','docs'),
(30501,'electrocasnice','Electrocasnice','Fier de călcat','docs'),
(30502,'electrocasnice','Electrocasnice','Cafetieră','docs'),
(30503,'electrocasnice','Electrocasnice','Uscător păr','docs'),
(30504,'electrocasnice','Electrocasnice','Toaster','docs'),
(30505,'electrocasnice','Electrocasnice','DVD','docs'),
(30506,'electrocasnice','Electrocasnice','Mașină de spălat rufe','docs'),
(30507,'electrocasnice','Electrocasnice','Sandwich-maker','docs'),
(30508,'electrocasnice','Electrocasnice','Frigider','docs'),
(30509,'electrocasnice','Electrocasnice','Cuptor microunde','docs'),
(30510,'electrocasnice','Electrocasnice','Aragaz','docs'),
(30511,'electrocasnice','Electrocasnice','Hotă','docs'),
(30512,'electrocasnice','Electrocasnice','Mașină de spălat vase','docs'),
(30513,'electrocasnice','Electrocasnice','Robot bucătărie','docs'),
(30514,'electrocasnice','Electrocasnice','Aspirator','docs'),
(30515,'electrocasnice','Electrocasnice','TV','docs'),
(30516,'electrocasnice','Electrocasnice','HI-FI','docs'),
(30601,'diverse','Diverse','Jacuzzi','docs'),
(30602,'diverse','Diverse','Scară interioară','docs'),
(30603,'diverse','Diverse','Șemineu','docs'),
(30604,'diverse','Diverse','Senzor de fum','docs'),
(30605,'diverse','Diverse','Sistem de alarmă','docs'),
(30606,'diverse','Diverse','Telecomandă poartă garaj','docs'),
(30607,'diverse','Diverse','Telecomandă poartă acces auto','docs');