// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfobqeycviqckzjyokxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmb2JxZXljdmlxY2t6anlva3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDk1NjgsImV4cCI6MjA3MTk4NTU2OH0.FcSHvGjPEkUVKtPvjQqlwErNdizEPX2YeBFc20O4dnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});